apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-fast-food-orders-config
  namespace: default
  labels:
    app: fiap-fast-food-app-orders
data:
  PORT: "3333"
  AWS_REGION: "us-west-2"
  NODE_ENV: "production"
  SQS_ORDER_QUEUE_URL: ${SQS_ORDER_QUEUE_URL}
  SNS_ORDER_TOPIC_ARN: ${SNS_ORDER_TOPIC_ARN}
