apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiap-fast-food-app-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: a9bc5a5347c0a4f9782f235eee8189d7-5f0748248687d86e.elb.us-west-2.amazonaws.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fiap-fast-food-app-orders
                port:
                  number: 80
          - path: /payment
            pathType: Prefix
            backend:
              service:
                name: fiap-fast-food-app-payments
                port:
                  number: 80
          - path: /production
            pathType: Prefix
            backend:
              service:
                name: fiap-fast-food-app-production
                port:
                  number: 80
